require('core.plugin_config.lualine')
require('core.plugin_config.blankline')
require('core.plugin_config.git')
require('core.plugin_config.ale')
require('core.plugin_config.treesitter')
require('core.plugin_config.telescope')
require('core.plugin_config.lsp')
